<?php

define('ERREUR_ENREGISTREMENT', 0);
define('ERREUR_IDENTIFIANTS', 1);
define('ERREUR_NBDERESERVATION', 2);
define('ERREUR_NBCASQUESENFANTS', 3);
define('ERREUR_NBLUGESETE', 4);
define('ERREUR_EMAIL', 5);
define('ERREUR_TELEPHONE', 6);
define('ERREUR_ADRESSE', 7);
define('ERREUR_MDP_TAILLE', 8);
define('ERREUR_MDP_IDENTIQUE', 9);
define('ERREUR_MDP_ABSENT', 10);

?>